version: 2 
  
jobs: 
  deploy to Production: 
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to Production
          command: . build/setup-prod.sh
      - run:
          name: Deploy to Production Org
          command: . build/deploy-prod.sh

 

  deploy to QA:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to QA
          command: . build/setup-qa.sh
      - run:
          name: Deploy to QA Org
          command: . build/deploy-qa.sh
          
          
  deploy to UAT:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: . build/install.sh
      - run:
          name: Login to UAT
          command: . build/setup-uat.sh
      - run:
          name: Deploy to UAT Org
          command: . build/deploy-uat.sh
        
workflows:
  version: 2
  validate:
    jobs:           
      - deploy to QA:
           filters:
            branches:
              only:
                - qa
      - deploy to UAT:
           filters:
            branches:
              only:
                - uat               
      - deploy to Production:
           filters:
            branches:
              only: 
                - master  